version: '3.8'

services:
  # Configuración del contenedor de la base de datos MySQL
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  # Contraseña de root para MySQL
      MYSQL_DATABASE: test      # Nombre de la base de datos
      MYSQL_USER: admin         # Nombre de usuario de MySQL
      MYSQL_PASSWORD: root      # Contraseña del usuario de MySQL
    ports:
      - "3306:3306"             # Mapeo de puertos (puerto_host:puerto_contenedor)
    volumes:
      - ./database:/var/lib/mysql  # Volumen para persistencia de datos de la base de datos
    
  # Configuración del contenedor de PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"              # Mapeo de puertos (puerto_host:puerto_contenedor)
    environment:
      PMA_HOST: db             # Host de la base de datos MySQL a la que se conecta PhpMyAdmin
      MYSQL_ROOT_PASSWORD: root  # Contraseña de root para MySQL
