version: '3.8'
services:
  # Servicio de Mongo como base de datos.
  mongodb:
    #La versión más reciente
    image: mongo:latest 
    #Nombre del contenedor que aparecerá al ejecutar 'docker ps' y al que Express se conectará.
    container_name: mongodb 
    # Variables de entorno para conectarse a mongo.
    environment:
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
    #Se mapea el puerto 27017 del contenedor al 27018 del anfitrión.
      - 27018:27017 
    volumes:
     - ./database:/data/db
     
  mongo-express:
    image: mongo-express:latest 
    container_name: mongo-express
    # El contenedor se reinicia hasta conectarse o hasta que el usuario lo detenga.
    restart: unless-stopped 
    ports:
    #Acceso a mongo-express en el puerto 8081.
      - 8081:8081
    environment:
    #El admin de la base de datos es root.
      ME_CONFIG_MONGODB_ADMINUSERNAME: root 
      #Contraseña para acceder a la base de datos.
      ME_CONFIG_MONGODB_ADMINPASSWORD: password 
      #El nombre del servidor al que se conecta es el propio contenedor. Por defecto es 'mongo'.
      ME_CONFIG_MONGODB_SERVER: mongodb
